version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=euller
      - MONGO_INITDB_ROOT_PASSWORD=12345
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
      - api_pagamento-mongodb-network
networks:
  api_pagamento-mongodb-network:
    driver: bridge
