server:
  port:
    8080
spring:
  data:
    mongodb:
      uri: mongodb://euller:12345@localhost:27017/db?authSource=admin

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG